---
title: "qaWriteUp"
output: html_document
date: "2022-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
weekly_visits <- read_excel("Downloads/Web Analytics at Quality Alloys.xls", 
    sheet = "Weekly Visits", range = "A5:H71")
View(weekly_visits)

financials <- read_excel("Downloads/Web Analytics at Quality Alloys.xls", 
    sheet = "Financials", range = "A5:E71")
View(financials)
```

```{r}
library(tidyverse)
visits_and_financials = weekly_visits %>%
  left_join(financials, by = 'Week (2008-2009)') %>%
  rename(week = `Week (2008-2009)`) %>%
  mutate(id = row_number(), period = as.factor(ifelse(id < 15, 1, ifelse(id < 36, 2, ifelse(id < 53, 3, 4)))))
  

```

```{r}
visits_and_financials %>%
  arrange(id) %>%
  ggplot(mapping = aes(x = id, y = Visits))+geom_col(aes(fill = period))+theme(axis.text.x=element_text(angle = 90))
```

```{r}
ggplot(data = visits_and_financials, mapping = aes(x = Visits, y = `Avg. Time on Site (secs.)`))+geom_point()+geom_smooth(method = 'lm', se = FALSE)


#mod = lm(Revenue~Visits, data = visits_and_financials)
#summary(mod)
```
```{r}
mod1 = lm(`Avg. Time on Site (secs.)`~Visits, data = visits_and_financials)
summary(mod)
```
```{r}
ggplot(data = visits_and_financials, mapping = aes(x = Visits, y = Revenue))+geom_point()
```

